from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import cast

ROOT = Path(__file__).resolve().parents[1]
SIGNATURE_SCHEMA_ID = "https://schemas.sangrep.com/contracts/sangrep-pack-signature-v1.json"
TARGETS = (
    (
        ROOT / "schemas/sangrep-pack-signature-v1.json",
        ROOT / "src/sangrep_contracts/generated/pack_signature_v1.py",
        "Pack signature and trust-root wire types generated from JSON Schema.",
    ),
    (
        ROOT / "schemas/sangrep-pack-manifest-v1.json",
        ROOT / "src/sangrep_contracts/generated/pack_manifest_v1.py",
        "Pack manifest and catalog wire types generated from JSON Schema.",
    ),
)


def _wire_name(reference: str) -> str:
    return f"{reference.rsplit('/', maxsplit=1)[-1]}Wire"


def _literal(value: object) -> str:
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    return repr(value)


def _type_expression(schema: object) -> str:
    if not isinstance(schema, dict):
        return "object"
    reference = schema.get("$ref")
    if isinstance(reference, str):
        return _wire_name(reference)
    if "const" in schema:
        return f"Literal[{_literal(schema['const'])}]"
    enum = schema.get("enum")
    if isinstance(enum, list) and enum:
        rendered = ", ".join(_literal(item) for item in enum)
        if len(rendered) > 72:
            return f"Literal[\n        {rendered}\n    ]"
        return f"Literal[{rendered}]"
    one_of = schema.get("oneOf")
    if isinstance(one_of, list) and one_of:
        return " | ".join(_type_expression(item) for item in one_of)
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            "None" if item == "null" else _type_expression({"type": item}) for item in schema_type
        )
    if schema_type == "string":
        return "str"
    if schema_type == "integer":
        return "int"
    if schema_type == "boolean":
        return "bool"
    if schema_type == "null":
        return "None"
    if schema_type == "array":
        return f"list[{_type_expression(schema.get('items', {}))}]"
    if schema_type == "object":
        return "dict[str, object]"
    return "object"


def _external_signature_refs(value: object) -> set[str]:
    found: set[str] = set()
    if isinstance(value, dict):
        reference = value.get("$ref")
        if isinstance(reference, str) and reference.startswith(f"{SIGNATURE_SCHEMA_ID}#/"):
            found.add(_wire_name(reference))
        for item in value.values():
            found.update(_external_signature_refs(item))
    elif isinstance(value, list):
        for item in value:
            found.update(_external_signature_refs(item))
    return found


def render_module(schema: dict[str, object], *, docstring: str) -> str:
    definitions = schema.get("$defs")
    if not isinstance(definitions, dict) or not definitions:
        raise ValueError("schema definitions are required")
    external_refs = _external_signature_refs(schema)
    lines = [
        f'"""{docstring}"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Literal, TypeAlias, TypedDict",
    ]
    if external_refs:
        names = sorted(external_refs)
        if len(names) == 1:
            lines.extend(["", f"from .pack_signature_v1 import {names[0]}"])
        else:
            lines.extend(
                [
                    "",
                    "from .pack_signature_v1 import (",
                    *(f"    {name}," for name in names),
                    ")",
                ]
            )
    lines.extend(["", "# Generated by tools/build_schema_types.py; do not edit by hand."])
    exported: list[str] = []
    for name, raw_definition in definitions.items():
        if not isinstance(name, str) or not isinstance(raw_definition, dict):
            raise ValueError("schema definition is malformed")
        wire_name = f"{name}Wire"
        exported.append(wire_name)
        properties = raw_definition.get("properties")
        if raw_definition.get("type") == "object" and isinstance(properties, dict):
            required = raw_definition.get("required", [])
            if not isinstance(required, list) or set(required) != set(properties):
                raise ValueError(f"{name} must have only required wire fields")
            lines.extend(["", "", f"class {wire_name}(TypedDict):"])
            if not properties:
                lines.append("    pass")
            for property_name, property_schema in properties.items():
                if not isinstance(property_name, str) or not property_name.isidentifier():
                    raise ValueError(f"{name} contains a non-identifier property")
                lines.append(f"    {property_name}: {_type_expression(property_schema)}")
        else:
            lines.extend(["", "", f"{wire_name}: TypeAlias = {_type_expression(raw_definition)}"])
    lines.extend(
        [
            "",
            "",
            "__all__ = (",
            *(f'    "{name}",' for name in sorted(exported)),
            ")",
            "",
        ]
    )
    return "\n".join(lines)


def _write_or_check(path: Path, content: str, *, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    current = True
    for schema_path, output_path, docstring in TARGETS:
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        content = render_module(cast(dict[str, object], schema), docstring=docstring)
        current = _write_or_check(output_path, content, check=arguments.check) and current
    if arguments.check and not current:
        print("schema-type-drift: generated types are not current")
        return 1
    if arguments.check:
        print("schema-type-drift: passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
